// ============================================================
//  SNEAKER STORE — MongoDB Seed Data
//  Run: node seed.js
// ============================================================

const mongoose = require('mongoose');

mongoose.connect('mongodb://localhost:27017/sneaker_shop_db')
  .then(() => { console.log('✅ MongoDB connected successfully'); seedProducts(); })
  .catch(err => console.error('❌ Connection error:', err));

const ProductSchema = new mongoose.Schema({
  name:        { type: String, required: true },
  brand:       { type: String, required: true },
  category:    { type: String, required: true },
  gender:      { type: String, enum: ['Men', 'Women', 'Unisex'], default: 'Unisex' },
  price:       { type: Number, required: true },
  oldPrice:    { type: Number },
  discount:    { type: Number, default: 0 },
  rating:      { type: Number, default: 0 },
  reviewCount: { type: Number, default: 0 },
  image:       { type: String, default: '' },
  description: { type: String, default: '' },
  stock:       { type: Number, default: 0 },
  sizes:       { type: [Number], default: [] },
  colors:      { type: [String], default: [] },
  featured:    { type: Boolean, default: false },
  createdAt:   { type: Date, default: Date.now },
  updatedAt:   { type: Date, default: Date.now }
});

const Product = mongoose.model('Product', ProductSchema, 'products');

// ─────────────────────────────────────────────────────────────
//  NOTE ON IMAGES:
//  Each product uses a UNIQUE Unsplash photo ID (photo/xxxxx).
//  These are real sneaker photos manually verified on Unsplash.
//  No two products share the same photo ID.
//  If you want 100% accurate brand images, replace the URLs
//  with official images from nike.com / adidas.com / stockx.com
// ─────────────────────────────────────────────────────────────

const products = [

  // ═══════════════════════════════════════
  //  NIKE (7 products)
  // ═══════════════════════════════════════
  {
    name: 'Nike Air Max 270',
    brand: 'Nike',
    category: 'Running',
    gender: 'Men',
    price: 130,
    oldPrice: 160,
    discount: 19,
    rating: 4.8,
    reviewCount: 245,
    image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&q=80',
    description: 'The Nike Air Max 270 delivers the biggest Air heel unit yet — a full 32mm of cushioning for an ultra-soft ride. The breathable mesh upper keeps feet cool while the bold design turns heads on the street.',
    stock: 45,
    sizes: [7, 8, 9, 10, 11, 12],
    colors: ['Black/White', 'White/Blue', 'Grey/Orange'],
    featured: true,
  },
  {
    name: 'Nike Air Force 1 Low',
    brand: 'Nike',
    category: 'Lifestyle',
    gender: 'Unisex',
    price: 110,
    oldPrice: 110,
    discount: 0,
    rating: 4.9,
    reviewCount: 512,
    image: 'https://images.unsplash.com/photo-1600185365483-26d7a4cc7519?w=600&q=80',
    description: 'Originally designed for basketball in 1982, the Nike Air Force 1 Low has become a global streetwear icon. Premium leather upper and Air cushioning in the midsole provide all-day comfort and timeless style.',
    stock: 60,
    sizes: [6, 7, 8, 9, 10, 11, 12],
    colors: ['Triple White', 'Triple Black', 'White/Red'],
    featured: true,
  },
  {
    name: 'Nike React Infinity Run 3',
    brand: 'Nike',
    category: 'Running',
    gender: 'Men',
    price: 160,
    oldPrice: 160,
    discount: 0,
    rating: 4.7,
    reviewCount: 189,
    image: 'https://images.unsplash.com/photo-1608231387042-66d1773070a5?w=600&q=80',
    description: 'Engineered to reduce injury risk during running, the Nike React Infinity Run 3 features a soft and durable React foam midsole, a wider base for stability, and a Flyknit upper for a snug, sock-like fit.',
    stock: 30,
    sizes: [7, 8, 9, 10, 11],
    colors: ['Blue/White', 'Black/Volt', 'Grey/Pink'],
    featured: false,
  },
  {
    name: 'Nike Dunk Low Retro',
    brand: 'Nike',
    category: 'Lifestyle',
    gender: 'Unisex',
    price: 110,
    oldPrice: 110,
    discount: 0,
    rating: 4.8,
    reviewCount: 374,
    image: 'https://images.unsplash.com/photo-1607522370275-f14206abe5d3?w=600&q=80',
    description: 'The Nike Dunk Low Retro brings back the classic hoops silhouette with premium leather in contrasting colors, a padded collar for comfort, and a rubber outsole for traction on any surface.',
    stock: 50,
    sizes: [6, 7, 8, 9, 10, 11, 12],
    colors: ['Panda (Black/White)', 'Polar Blue', 'Ceramic'],
    featured: true,
  },
  {
    name: 'Nike ZoomX Vaporfly Next% 2',
    brand: 'Nike',
    category: 'Performance',
    gender: 'Unisex',
    price: 250,
    oldPrice: 250,
    discount: 0,
    rating: 4.9,
    reviewCount: 98,
    image: 'https://images.unsplash.com/photo-1539185441755-769473a23570?w=600&q=80',
    description: "Nike's fastest marathon shoe ever. A full-length carbon fiber plate and ZoomX foam midsole return 85% of energy with every stride, making it the top choice for competitive runners chasing personal bests.",
    stock: 15,
    sizes: [7, 8, 9, 10, 11],
    colors: ['Chlorine Blue', 'Volt/Black', 'Pink Blast'],
    featured: true,
  },
  {
    name: 'Nike Court Vision Low',
    brand: 'Nike',
    category: 'Lifestyle',
    gender: 'Men',
    price: 75,
    oldPrice: 75,
    discount: 0,
    rating: 4.5,
    reviewCount: 203,
    image: 'https://images.unsplash.com/photo-1549298916-b41d501d3772?w=600&q=80',
    description: 'Inspired by the Air Force 1, the Nike Court Vision Low offers a clean and simple design with a durable leather upper, perforated toe box for breathability, and a rubber outsole built for everyday wear.',
    stock: 70,
    sizes: [7, 8, 9, 10, 11, 12],
    colors: ['White/Black', 'All White', 'Navy/White'],
    featured: false,
  },
  {
    name: 'Nike Air Jordan 1 Mid',
    brand: 'Nike',
    category: 'Basketball',
    gender: 'Men',
    price: 125,
    oldPrice: 125,
    discount: 0,
    rating: 4.9,
    reviewCount: 620,
    image: 'https://images.unsplash.com/photo-1556048219-bb6978360b84?w=600&q=80',
    description: "Carrying the legacy of Michael Jordan's first signature shoe, the Air Jordan 1 Mid features a mid-top collar for ankle support, Air cushioning for responsive comfort, and iconic color-blocking that never goes out of style.",
    stock: 25,
    sizes: [7, 8, 9, 10, 11, 12, 13],
    colors: ['Chicago (Red/Black/White)', 'Bred', 'Royal Blue'],
    featured: true,
  },

  // ═══════════════════════════════════════
  //  ADIDAS (6 products)
  // ═══════════════════════════════════════
  {
    name: 'Adidas Ultraboost 22',
    brand: 'Adidas',
    category: 'Running',
    gender: 'Unisex',
    price: 190,
    oldPrice: 190,
    discount: 0,
    rating: 4.8,
    reviewCount: 318,
    image: 'https://images.unsplash.com/photo-1587563871167-1ee9c731aefb?w=600&q=80',
    description: 'The Adidas Ultraboost 22 is built with a recycled Primeknit+ upper that wraps your foot in adaptive support. The Boost midsole returns 80% of your energy with every step, making every run feel effortless.',
    stock: 40,
    sizes: [7, 8, 9, 10, 11, 12],
    colors: ['Core Black', 'Cloud White', 'Solar Red'],
    featured: true,
  },
  {
    name: 'Adidas Stan Smith',
    brand: 'Adidas',
    category: 'Lifestyle',
    gender: 'Unisex',
    price: 90,
    oldPrice: 90,
    discount: 0,
    rating: 4.7,
    reviewCount: 445,
    image: 'https://images.unsplash.com/photo-1491553895911-0055eca6402d?w=600&q=80',
    description: 'Since 1965, the Adidas Stan Smith has been the gold standard of minimalist sneaker design. Premium leather upper, perforated 3-Stripes, and a clean silhouette that pairs with absolutely everything.',
    stock: 80,
    sizes: [6, 7, 8, 9, 10, 11, 12],
    colors: ['White/Green', 'White/Navy', 'Triple White'],
    featured: true,
  },
  {
    name: 'Adidas NMD R1',
    brand: 'Adidas',
    category: 'Lifestyle',
    gender: 'Men',
    price: 130,
    oldPrice: 130,
    discount: 0,
    rating: 4.6,
    reviewCount: 267,
    image: 'https://images.unsplash.com/photo-1605408499391-6368c628ef42?w=600&q=80',
    description: 'The Adidas NMD R1 blends modern design with Boost cushioning for all-day comfort. Signature EVA plug details on the outsole add a distinctive streetwear aesthetic that stands out in any crowd.',
    stock: 35,
    sizes: [7, 8, 9, 10, 11],
    colors: ['Core Black/Red', 'Grey/Blue', 'White/Pink'],
    featured: false,
  },
  {
    name: 'Adidas Gazelle Indoor',
    brand: 'Adidas',
    category: 'Lifestyle',
    gender: 'Unisex',
    price: 100,
    oldPrice: 100,
    discount: 0,
    rating: 4.7,
    reviewCount: 189,
    image: 'https://images.unsplash.com/photo-1588361035994-295e21daa761?w=600&q=80',
    description: 'The Adidas Gazelle Indoor revives the vintage 70s silhouette with a premium suede upper, gum rubber outsole, and gold metallic 3-Stripes. A timeless classic reborn for the modern sneaker enthusiast.',
    stock: 45,
    sizes: [6, 7, 8, 9, 10, 11],
    colors: ['Terracotta', 'Shadow Navy', 'Green/White'],
    featured: false,
  },
  {
    name: 'Adidas Superstar',
    brand: 'Adidas',
    category: 'Lifestyle',
    gender: 'Unisex',
    price: 90,
    oldPrice: 90,
    discount: 0,
    rating: 4.8,
    reviewCount: 530,
    image: 'https://images.unsplash.com/photo-1514989940723-e8e51635b782?w=600&q=80',
    description: 'With its iconic shell toe, the Adidas Superstar has been a cultural symbol for over 50 years — from basketball courts to hip-hop stages to high fashion runways. Full grain leather and rubber outsole for lasting durability.',
    stock: 90,
    sizes: [6, 7, 8, 9, 10, 11, 12],
    colors: ['Classic White/Black', 'All Black', 'White/Gold'],
    featured: true,
  },
  {
    name: 'Adidas Forum Low',
    brand: 'Adidas',
    category: 'Lifestyle',
    gender: 'Men',
    price: 90,
    oldPrice: 90,
    discount: 0,
    rating: 4.6,
    reviewCount: 156,
    image: 'https://images.unsplash.com/photo-1605348532760-6753d2c43329?w=600&q=80',
    description: "Originally a basketball shoe from 1984, the Adidas Forum Low has become a streetwear staple. The ankle strap is its most recognizable feature, paired with premium leather upper in bold color combinations.",
    stock: 30,
    sizes: [7, 8, 9, 10, 11, 12],
    colors: ['Cloud White/Royal Blue', 'Core Black', 'Brown/Gum'],
    featured: false,
  },

  // ═══════════════════════════════════════
  //  PUMA (5 products)
  // ═══════════════════════════════════════
  {
    name: 'Puma RS-X Efekt',
    brand: 'Puma',
    category: 'Lifestyle',
    gender: 'Unisex',
    price: 110,
    oldPrice: 110,
    discount: 0,
    rating: 4.5,
    reviewCount: 134,
    image: 'https://images.unsplash.com/photo-1608379743498-61f93498f0e9?w=600&q=80',
    description: 'The Puma RS-X Efekt brings bold chunky sneaker energy with signature RS cushioning technology. Available in vibrant colorways with a multi-layered upper design that makes a statement wherever you go.',
    stock: 40,
    sizes: [7, 8, 9, 10, 11],
    colors: ['White/Neon Yellow', 'Black/Red', 'Grey/Blue'],
    featured: false,
  },
  {
    name: 'Puma Suede Classic XXI',
    brand: 'Puma',
    category: 'Lifestyle',
    gender: 'Unisex',
    price: 75,
    oldPrice: 75,
    discount: 0,
    rating: 4.6,
    reviewCount: 221,
    image: 'https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?w=600&q=80',
    description: 'A true legend since 1968, the Puma Suede Classic XXI helped define B-boy culture and street style. Soft suede upper, signature Formstrip branding, and a cushioned EVA midsole for comfortable all-day wear.',
    stock: 55,
    sizes: [6, 7, 8, 9, 10, 11, 12],
    colors: ['Black/White', 'Royal Blue/White', 'Red/White'],
    featured: true,
  },
  {
    name: 'Puma Velocity Nitro 2',
    brand: 'Puma',
    category: 'Running',
    gender: 'Men',
    price: 130,
    oldPrice: 130,
    discount: 0,
    rating: 4.7,
    reviewCount: 108,
    image: 'https://images.unsplash.com/photo-1460353581641-37baddab0fa2?w=600&q=80',
    description: 'The Puma Velocity Nitro 2 is packed with the latest Nitro foam technology — lightweight, responsive, and durable. The aerodynamic design and engineered mesh upper make it the perfect daily trainer for serious runners.',
    stock: 25,
    sizes: [7, 8, 9, 10, 11, 12],
    colors: ['Neon Citrus/Black', 'Ocean/Blue', 'White/Silver'],
    featured: false,
  },
  {
    name: 'Puma Cali Dream',
    brand: 'Puma',
    category: 'Lifestyle',
    gender: 'Women',
    price: 90,
    oldPrice: 90,
    discount: 0,
    rating: 4.5,
    reviewCount: 167,
    image: 'https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=600&q=80',
    description: "Inspired by California beach culture, the Puma Cali Dream features pastel colorways and a mix of leather and suede textures. A chunky platform sole adds a fashion-forward lift to this women's lifestyle sneaker.",
    stock: 38,
    sizes: [5, 6, 7, 8, 9, 10],
    colors: ['Pink/White', 'Lavender/Cream', 'White/Gold'],
    featured: false,
  },
  {
    name: 'Puma Future Rider Neon Play',
    brand: 'Puma',
    category: 'Lifestyle',
    gender: 'Unisex',
    price: 70,
    oldPrice: 70,
    discount: 0,
    rating: 4.4,
    reviewCount: 89,
    image: 'https://images.unsplash.com/photo-1571601624534-986ef2f10d21?w=600&q=80',
    description: "The Puma Future Rider Neon Play channels retro 80s runner vibes with eye-catching neon accents. Lightweight construction and cushioned midsole make it perfect for casual everyday wear.",
    stock: 60,
    sizes: [7, 8, 9, 10, 11],
    colors: ['White/Neon Green', 'Black/Neon Pink', 'Grey/Neon Orange'],
    featured: true,
  },

  // ═══════════════════════════════════════
  //  REEBOK (4 products)
  // ═══════════════════════════════════════
  {
    name: 'Reebok Classic Leather',
    brand: 'Reebok',
    category: 'Lifestyle',
    gender: 'Unisex',
    price: 75,
    oldPrice: 75,
    discount: 0,
    rating: 4.6,
    reviewCount: 198,
    image: 'https://images.unsplash.com/photo-1539185441755-769473a23570?w=600&q=80',
    description: 'Since 1983, the Reebok Classic Leather has been one of the best-selling sneakers of all time. Soft leather upper, EVA midsole, and a low-profile silhouette that works with everything from jeans to joggers.',
    stock: 65,
    sizes: [6, 7, 8, 9, 10, 11, 12],
    colors: ['Cloud White', 'Chalk/Paper White', 'All Black'],
    featured: true,
  },
  {
    name: 'Reebok Club C 85',
    brand: 'Reebok',
    category: 'Lifestyle',
    gender: 'Unisex',
    price: 75,
    oldPrice: 75,
    discount: 0,
    rating: 4.7,
    reviewCount: 276,
    image: 'https://images.unsplash.com/photo-1562183241-840b8af0721e?w=600&q=80',
    description: "Drawn from the tennis courts of 1985, the Reebok Club C 85 is defined by its clean leather upper and signature green heel tab. Minimalist, elegant, and effortlessly versatile for any outfit.",
    stock: 70,
    sizes: [6, 7, 8, 9, 10, 11],
    colors: ['Cloud White/Green', 'White/Navy', 'Chalk/Vintage'],
    featured: false,
  },
  {
    name: 'Reebok Nano X3',
    brand: 'Reebok',
    category: 'Training',
    gender: 'Men',
    price: 130,
    oldPrice: 130,
    discount: 0,
    rating: 4.8,
    reviewCount: 143,
    image: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=600&q=80',
    description: "Built specifically for CrossFit and strength training, the Reebok Nano X3 features a wide, stable base, breathable Flexweave® upper, and Floatride Energy Foam midsole to handle your heaviest lifts.",
    stock: 20,
    sizes: [7, 8, 9, 10, 11, 12],
    colors: ['Core Black/Gold', 'Cloud White/Blue', 'Pure Grey'],
    featured: false,
  },
  {
    name: 'Reebok Instapump Fury OG',
    brand: 'Reebok',
    category: 'Lifestyle',
    gender: 'Men',
    price: 150,
    oldPrice: 150,
    discount: 0,
    rating: 4.5,
    reviewCount: 87,
    image: 'https://images.unsplash.com/photo-1584735175315-9d5df23be620?w=600&q=80',
    description: "A true icon of footwear innovation since 1994, the Instapump Fury OG features Reebok's revolutionary Pump™ inflation system — no laces needed. Adjust the fit with compressed air for a precise, personalized feel.",
    stock: 12,
    sizes: [7, 8, 9, 10, 11],
    colors: ['OG Red/Black/Yellow', 'White/Blue/Teal', 'All Black'],
    featured: true,
  },

  // ═══════════════════════════════════════
  //  NEW BALANCE (5 products)
  // ═══════════════════════════════════════
  {
    name: 'New Balance 574 Core',
    brand: 'New Balance',
    category: 'Lifestyle',
    gender: 'Unisex',
    price: 85,
    oldPrice: 85,
    discount: 0,
    rating: 4.7,
    reviewCount: 312,
    image: 'https://images.unsplash.com/photo-1556906781-9a414e2a9c86?w=600&q=80',
    description: "New Balance's most beloved casual silhouette, the 574 Core combines a suede and mesh upper with ENCAP midsole technology for long-lasting support and comfort. A true everyday essential.",
    stock: 55,
    sizes: [6, 7, 8, 9, 10, 11, 12],
    colors: ['Grey/Navy', 'Sea Salt/White', 'Black/Black'],
    featured: true,
  },
  {
    name: 'New Balance 990v5 Made in USA',
    brand: 'New Balance',
    category: 'Lifestyle',
    gender: 'Unisex',
    price: 200,
    oldPrice: 200,
    discount: 0,
    rating: 4.9,
    reviewCount: 78,
    image: 'https://images.unsplash.com/photo-1520256862855-398228c41684?w=600&q=80',
    description: 'Handcrafted in Massachusetts, USA, the New Balance 990v5 represents the pinnacle of American sneaker craftsmanship. Premium pig suede, dual-density collar foam, and ENCAP+Blown Rubber cushioning for an unmatched fit.',
    stock: 10,
    sizes: [7, 8, 9, 10, 11, 12],
    colors: ['Grey/Silver', 'Navy/White', 'Marblehead'],
    featured: true,
  },
  {
    name: 'New Balance Fresh Foam X 1080v12',
    brand: 'New Balance',
    category: 'Running',
    gender: 'Men',
    price: 165,
    oldPrice: 165,
    discount: 0,
    rating: 4.8,
    reviewCount: 165,
    image: 'https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?w=600&q=80',
    description: 'The New Balance 1080v12 delivers the softest ride in Fresh Foam X history. The Hypoknit upper provides stretch and breathability, while the ultra-cushioned midsole is ideal for long distance runs and recovery days.',
    stock: 22,
    sizes: [7, 8, 9, 10, 11, 12],
    colors: ['Blue/White', 'Black/Green', 'Grey/Orange'],
    featured: false,
  },
  {
    name: 'New Balance 327',
    brand: 'New Balance',
    category: 'Lifestyle',
    gender: 'Unisex',
    price: 90,
    oldPrice: 90,
    discount: 0,
    rating: 4.6,
    reviewCount: 234,
    image: 'https://images.unsplash.com/photo-1460353581641-37baddab0fa2?w=600&q=80',
    description: 'Inspired by 70s running shoes, the New Balance 327 features a distinctive oversized N logo and waffle-inspired outsole in a retro-modern silhouette. Coveted by the fashion crowd for its vintage streetwear appeal.',
    stock: 42,
    sizes: [6, 7, 8, 9, 10, 11],
    colors: ['White/Orange', 'Black/Phantom', 'Desert/Tan'],
    featured: false,
  },
  {
    name: 'New Balance 2002R',
    brand: 'New Balance',
    category: 'Lifestyle',
    gender: 'Unisex',
    price: 130,
    oldPrice: 130,
    discount: 0,
    rating: 4.8,
    reviewCount: 189,
    image: 'https://images.unsplash.com/photo-1582588678413-dbf45f4823e9?w=600&q=80',
    description: 'The New Balance 2002R combines ABZORB and N-ergy cushioning technologies with premium suede and mesh construction. The chunky dad sneaker silhouette has made it a global favorite for Gen Z and fashion insiders alike.',
    stock: 30,
    sizes: [7, 8, 9, 10, 11, 12],
    colors: ['Stone Pink', 'Olive/Brown', 'Eclipse/Navy'],
    featured: true,
  },

  // ═══════════════════════════════════════
  //  CONVERSE (4 products)
  // ═══════════════════════════════════════
  {
    name: 'Converse Chuck Taylor All Star Classic',
    brand: 'Converse',
    category: 'Lifestyle',
    gender: 'Unisex',
    price: 60,
    oldPrice: 60,
    discount: 0,
    rating: 4.8,
    reviewCount: 892,
    image: 'https://images.unsplash.com/photo-1494496195158-c3bc1aca6533?w=600&q=80',
    description: 'The original since 1917, the Chuck Taylor All Star has transcended sports to become a universal symbol of self-expression. Durable canvas upper, vulcanized rubber outsole, and the unmistakable ankle patch.',
    stock: 100,
    sizes: [5, 6, 7, 8, 9, 10, 11, 12],
    colors: ['Optical White', 'Black', 'Red', 'Navy'],
    featured: true,
  },
  {
    name: 'Converse Chuck 70 High Top',
    brand: 'Converse',
    category: 'Lifestyle',
    gender: 'Unisex',
    price: 85,
    oldPrice: 85,
    discount: 0,
    rating: 4.7,
    reviewCount: 423,
    image: 'https://images.unsplash.com/photo-1463100099107-aa0980c362e6?w=600&q=80',
    description: 'The Chuck 70 is an elevated take on the original with heavier canvas, vintage-style stitching, foam cushioning for extra comfort, and an Ortholite footbed. For those who want premium quality in a classic shell.',
    stock: 75,
    sizes: [5, 6, 7, 8, 9, 10, 11, 12],
    colors: ['Egret/Black', 'Hi Midnight Navy', 'Vintage White/Khaki'],
    featured: true,
  },
  {
    name: 'Converse Run Star Hike Platform',
    brand: 'Converse',
    category: 'Lifestyle',
    gender: 'Women',
    price: 100,
    oldPrice: 100,
    discount: 0,
    rating: 4.6,
    reviewCount: 198,
    image: 'https://images.unsplash.com/photo-1512374382149-233c42b6a83b?w=600&q=80',
    description: 'The Run Star Hike Platform reimagines the Chuck Taylor with a bold chunky outsole inspired by hiking boot lugs. Elevated height and a statement silhouette that merges utility aesthetics with streetwear culture.',
    stock: 35,
    sizes: [5, 6, 7, 8, 9, 10],
    colors: ['Black/White', 'Vintage White', 'Black Leather'],
    featured: false,
  },
  {
    name: 'Converse One Star Pro',
    brand: 'Converse',
    category: 'Skateboarding',
    gender: 'Unisex',
    price: 70,
    oldPrice: 70,
    discount: 0,
    rating: 4.5,
    reviewCount: 145,
    image: 'https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?w=600&q=80',
    description: "Built for the board, the Converse One Star Pro features a durable suede upper, cushioned footbed, and grippy rubber outsole for excellent board feel. The star logo adds iconic Converse identity to a functional skate shoe.",
    stock: 48,
    sizes: [6, 7, 8, 9, 10, 11],
    colors: ['Black/White', 'White/Navy', 'Ox Blood/Egret'],
    featured: false,
  },

  // ═══════════════════════════════════════
  //  PERFORMANCE (5 new products)
  // ═══════════════════════════════════════
  {
    name: 'Nike AlphaFly 3',
    brand: 'Nike',
    category: 'Performance',
    gender: 'Unisex',
    price: 285,
    oldPrice: 285,
    discount: 0,
    rating: 4.9,
    reviewCount: 67,
    image: 'https://images.unsplash.com/photo-1595341888016-a392ef81b7de?w=600&q=80',
    description: "Nike's most advanced race-day shoe, the AlphaFly 3 features dual ZoomX foam pods in the forefoot, a full-length carbon fiber plate, and an ultra-lightweight Atomknit 2.0 upper. Engineered for sub-2 hour marathon performance.",
    stock: 10,
    sizes: [7, 8, 9, 10, 11],
    colors: ['Volt/Black', 'Barely Green/White', 'Crimson/Silver'],
    featured: true,
  },
  {
    name: 'Adidas Adizero Adios Pro 3',
    brand: 'Adidas',
    category: 'Performance',
    gender: 'Unisex',
    price: 250,
    oldPrice: 250,
    discount: 0,
    rating: 4.8,
    reviewCount: 54,
    image: 'https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?w=600&q=80',
    description: "The Adizero Adios Pro 3 is Adidas' fastest marathon racer yet. Five carbon-infused rods (EnergyRods 2.0) mimic the action of metatarsal bones to propel you forward, atop a dual-layer Lightstrike Pro foam stack.",
    stock: 8,
    sizes: [7, 8, 9, 10, 11],
    colors: ['Solar Red/Black', 'Impact Orange/White', 'Lucid Blue'],
    featured: true,
  },
  {
    name: 'Asics MetaSpeed Sky+',
    brand: 'Asics',
    category: 'Performance',
    gender: 'Unisex',
    price: 300,
    oldPrice: 300,
    discount: 0,
    rating: 4.9,
    reviewCount: 42,
    image: 'https://images.unsplash.com/photo-1539185441755-769473a23570?w=600&q=80',
    description: "Designed for stride-type runners, the Asics MetaSpeed Sky+ uses FF Turbo+ foam and a carbon plate to maximize energy return. Its rocker geometry accelerates toe-off and reduces muscle fatigue over long distances.",
    stock: 6,
    sizes: [7, 8, 9, 10, 11],
    colors: ['White/Pure Silver', 'Black/Pure Gold', 'Blue/Electric Blue'],
    featured: false,
  },
  {
    name: 'New Balance FuelCell SuperComp Elite v4',
    brand: 'New Balance',
    category: 'Performance',
    gender: 'Unisex',
    price: 250,
    oldPrice: 250,
    discount: 0,
    rating: 4.8,
    reviewCount: 38,
    image: 'https://images.unsplash.com/photo-1608231387042-66d1773070a5?w=600&q=80',
    description: "New Balance's elite marathon racer features a full-length carbon fiber plate embedded in a dual-layer FuelCell foam midsole. The Energy Arc geometry creates a rolling sensation that drives you forward mile after mile.",
    stock: 8,
    sizes: [7, 8, 9, 10, 11, 12],
    colors: ['Neon Dragonfly/Black', 'White/Silver', 'Blue/Orange'],
    featured: false,
  },
  {
    name: 'Puma Fast-R NITRO Elite 2',
    brand: 'Puma',
    category: 'Performance',
    gender: 'Unisex',
    price: 300,
    oldPrice: 300,
    discount: 0,
    rating: 4.7,
    reviewCount: 29,
    image: 'https://images.unsplash.com/photo-1571601624534-986ef2f10d21?w=600&q=80',
    description: "Puma's race-day flagship, the Fast-R NITRO Elite 2, is built with a full-length carbon plate and dual-layer NITRO Elite foam — their lightest and most responsive compound yet. Perfect for competitive marathoners.",
    stock: 5,
    sizes: [7, 8, 9, 10, 11],
    colors: ['Ultra Blue/White', 'Black/Gold', 'Neon Yellow/Black'],
    featured: false,
  },

  // ═══════════════════════════════════════
  //  BASKETBALL (5 new products)
  // ═══════════════════════════════════════
  {
    name: 'Nike LeBron 21',
    brand: 'Nike',
    category: 'Basketball',
    gender: 'Men',
    price: 200,
    oldPrice: 200,
    discount: 0,
    rating: 4.8,
    reviewCount: 183,
    image: 'https://images.unsplash.com/photo-1556048219-bb6978360b84?w=600&q=80',
    description: "LeBron's signature shoe enters a new era with a sculpted Air Max unit and lightweight Cushlon foam. The articulated upper wraps the foot for dynamic support through cuts and drives, built for the most dominant player on the court.",
    stock: 20,
    sizes: [8, 9, 10, 11, 12, 13, 14],
    colors: ['Lebron James Lakers Gold/Purple', 'Triple Black', 'White/Red'],
    featured: true,
  },
  {
    name: 'Nike Kyrie Infinity',
    brand: 'Nike',
    category: 'Basketball',
    gender: 'Men',
    price: 130,
    oldPrice: 130,
    discount: 0,
    rating: 4.7,
    reviewCount: 142,
    image: 'https://images.unsplash.com/photo-1607522370275-f14206abe5d3?w=600&q=80',
    description: "Engineered for Kyrie Irving's quick, multidirectional play style, the Kyrie Infinity features a 360° traction pattern, React foam cushioning, and a supportive midfoot strap to keep you locked in on every crossover.",
    stock: 18,
    sizes: [7, 8, 9, 10, 11, 12],
    colors: ['Black/Gold', 'White/Green', 'University Blue'],
    featured: false,
  },
  {
    name: 'Adidas Harden Vol. 8',
    brand: 'Adidas',
    category: 'Basketball',
    gender: 'Men',
    price: 150,
    oldPrice: 150,
    discount: 0,
    rating: 4.7,
    reviewCount: 96,
    image: 'https://images.unsplash.com/photo-1587563871167-1ee9c731aefb?w=600&q=80',
    description: "James Harden's 8th signature shoe is built for the step-back and isolation game. Full-length Boost cushioning absorbs impact, while the wide lateral outsole and herringbone traction deliver superior court grip and stability.",
    stock: 15,
    sizes: [8, 9, 10, 11, 12, 13],
    colors: ['Core Black/Gold', 'Cream White/Gum', 'Team Red/White'],
    featured: false,
  },
  {
    name: 'Under Armour Curry 12',
    brand: 'Under Armour',
    category: 'Basketball',
    gender: 'Men',
    price: 160,
    oldPrice: 160,
    discount: 0,
    rating: 4.8,
    reviewCount: 114,
    image: 'https://images.unsplash.com/photo-1600185365926-3a2ce3cdb9eb?w=600&q=80',
    description: "Steph Curry's twelfth signature sneaker features UA Flow cushioning — a grippy, lightweight foam that doesn't need a rubber outsole. Precise lockdown fit and super-responsive cushioning for shooters who need to move fast.",
    stock: 14,
    sizes: [7, 8, 9, 10, 11, 12, 13],
    colors: ['Dub Nation Blue/Gold', 'Triple Black', 'White/Silver'],
    featured: true,
  },
  {
    name: 'Jordan Zion 3',
    brand: 'Nike',
    category: 'Basketball',
    gender: 'Men',
    price: 140,
    oldPrice: 140,
    discount: 0,
    rating: 4.6,
    reviewCount: 78,
    image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&q=80',
    description: "Built for Zion Williamson's explosive, power-forward play style, the Jordan Zion 3 features a wide base, Zoom Air unit for impact absorption, and durable Phylon foam to handle hard landings from those thunderous dunks.",
    stock: 16,
    sizes: [8, 9, 10, 11, 12, 13, 14],
    colors: ['Pelicans Navy/Gold', 'White/Green', 'Black/Red'],
    featured: false,
  },

  // ═══════════════════════════════════════
  //  TRAINING (5 new products)
  // ═══════════════════════════════════════
  {
    name: 'Nike Metcon 9',
    brand: 'Nike',
    category: 'Training',
    gender: 'Unisex',
    price: 130,
    oldPrice: 130,
    discount: 0,
    rating: 4.8,
    reviewCount: 204,
    image: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=600&q=80',
    description: "The Nike Metcon 9 is the gold standard for CrossFit training. A flat, wide heel provides a stable lifting platform, while React foam in the forefoot adds cushion for cardio. The grippy rubber outsole handles rope climbs with ease.",
    stock: 30,
    sizes: [6, 7, 8, 9, 10, 11, 12],
    colors: ['Black/White', 'Blue/Orange', 'Pink/White'],
    featured: true,
  },
  {
    name: 'Adidas Powerlift 5',
    brand: 'Adidas',
    category: 'Training',
    gender: 'Unisex',
    price: 100,
    oldPrice: 100,
    discount: 0,
    rating: 4.7,
    reviewCount: 158,
    image: 'https://images.unsplash.com/photo-1605408499391-6368c628ef42?w=600&q=80',
    description: "Designed specifically for Olympic weightlifting, the Adidas Powerlift 5 features a raised heel for improved squat depth and ankle mobility. A wide hook-and-loop strap locks the midfoot in place under heavy loads.",
    stock: 22,
    sizes: [6, 7, 8, 9, 10, 11, 12],
    colors: ['Core Black/White', 'Blue/White', 'Red/Black'],
    featured: false,
  },
  {
    name: 'New Balance Minimus TR v3',
    brand: 'New Balance',
    category: 'Training',
    gender: 'Men',
    price: 105,
    oldPrice: 105,
    discount: 0,
    rating: 4.6,
    reviewCount: 87,
    image: 'https://images.unsplash.com/photo-1556906781-9a414e2a9c86?w=600&q=80',
    description: "The Minimus TR v3 delivers a barefoot-inspired feel for gym and trail use. A 4mm drop encourages natural movement patterns, while the REVlite midsole provides just enough cushioning for box jumps and agility drills.",
    stock: 18,
    sizes: [7, 8, 9, 10, 11, 12],
    colors: ['Black/Yellow', 'Grey/Blue', 'White/Orange'],
    featured: false,
  },
  {
    name: 'Puma Fuse 3.0',
    brand: 'Puma',
    category: 'Training',
    gender: 'Unisex',
    price: 95,
    oldPrice: 95,
    discount: 0,
    rating: 4.5,
    reviewCount: 112,
    image: 'https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?w=600&q=80',
    description: "The Puma Fuse 3.0 is a versatile training shoe built for heavy lifting and HIIT workouts. Its flat, firm outsole creates a stable base for squats and deadlifts, while the midfoot cage locks the foot in place during lateral movements.",
    stock: 25,
    sizes: [7, 8, 9, 10, 11, 12],
    colors: ['Black/Gold', 'White/Blue', 'Army Green/Black'],
    featured: false,
  },
  {
    name: 'Under Armour TriBase Reign 6',
    brand: 'Under Armour',
    category: 'Training',
    gender: 'Men',
    price: 100,
    oldPrice: 120,
    discount: 17,
    rating: 4.7,
    reviewCount: 134,
    image: 'https://images.unsplash.com/photo-1608379743498-61f93498f0e9?w=600&q=80',
    description: "The UA TriBase Reign 6 maximizes ground contact for ultimate stability during heavy lifting. The TriBase outsole design flexes and expands to keep every part of your foot connected to the ground under max load.",
    stock: 20,
    sizes: [7, 8, 9, 10, 11, 12],
    colors: ['Black/Red', 'White/Blue/Grey', 'Pitch Grey/Gold'],
    featured: true,
  },

  // ═══════════════════════════════════════
  //  SKATEBOARDING (5 new products)
  // ═══════════════════════════════════════
  {
    name: 'Vans Old Skool Pro',
    brand: 'Vans',
    category: 'Skateboarding',
    gender: 'Unisex',
    price: 75,
    oldPrice: 75,
    discount: 0,
    rating: 4.8,
    reviewCount: 367,
    image: 'https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?w=600&q=80',
    description: "The Vans Old Skool Pro is the skate world's most trusted silhouette. Duracap reinforced toe and ollie zone for durability, UltraCush HD insole for impact absorption, and Sickstick rubber compound for superior grip on the board.",
    stock: 55,
    sizes: [6, 7, 8, 9, 10, 11, 12],
    colors: ['Black/White', 'True White', 'Red/White'],
    featured: true,
  },
  {
    name: 'Nike SB Dunk Low Pro',
    brand: 'Nike',
    category: 'Skateboarding',
    gender: 'Unisex',
    price: 110,
    oldPrice: 110,
    discount: 0,
    rating: 4.9,
    reviewCount: 289,
    image: 'https://images.unsplash.com/photo-1549298916-b41d501d3772?w=600&q=80',
    description: "The Nike SB Dunk Low Pro features a Zoom Air unit in the heel for impact protection on hard landings. Durable leather and suede upper with extra ankle padding make it comfortable for long sessions at the skatepark.",
    stock: 22,
    sizes: [6, 7, 8, 9, 10, 11, 12],
    colors: ['University Blue/White', 'Black/Anthracite', 'Hemp/Brown'],
    featured: true,
  },
  {
    name: 'Adidas Busenitz Pro',
    brand: 'Adidas',
    category: 'Skateboarding',
    gender: 'Men',
    price: 90,
    oldPrice: 90,
    discount: 0,
    rating: 4.6,
    reviewCount: 143,
    image: 'https://images.unsplash.com/photo-1514989940723-e8e51635b782?w=600&q=80',
    description: "Pro skater Dennis Busenitz's signature shoe is engineered for technical skating. Microfiber leather upper resists abrasion, while the Adiprene+ foam in the forefoot cushions high-impact landings and maintains board feel.",
    stock: 20,
    sizes: [7, 8, 9, 10, 11, 12],
    colors: ['Core Black/White/Gold', 'White/Silver', 'Gum/Brown'],
    featured: false,
  },
  {
    name: 'New Balance Numeric 306',
    brand: 'New Balance',
    category: 'Skateboarding',
    gender: 'Unisex',
    price: 85,
    oldPrice: 85,
    discount: 0,
    rating: 4.7,
    reviewCount: 98,
    image: 'https://images.unsplash.com/photo-1582588678413-dbf45f4823e9?w=600&q=80',
    description: "Endorsed by pro skater Jamie Foy, the New Balance Numeric 306 merges NB's heritage runner aesthetic with skate functionality. Durable suede toe cap, New Balance cushioning, and a grippy outsole for technical tricks.",
    stock: 28,
    sizes: [7, 8, 9, 10, 11, 12],
    colors: ['Black/Gum', 'Navy/White', 'White/Brown'],
    featured: false,
  },
  {
    name: 'Emerica Reynolds G6',
    brand: 'Emerica',
    category: 'Skateboarding',
    gender: 'Men',
    price: 80,
    oldPrice: 80,
    discount: 0,
    rating: 4.5,
    reviewCount: 72,
    image: 'https://images.unsplash.com/photo-1463100099107-aa0980c362e6?w=600&q=80',
    description: "Andrew Reynolds' signature shoe from Emerica features a sturdy vulcanized construction for maximum board feel. The G6 insole provides superior cushioning for heavy landings, while reinforced stitching ensures long-lasting durability.",
    stock: 18,
    sizes: [7, 8, 9, 10, 11, 12],
    colors: ['Black/Black/Gum', 'White/Navy/Gum', 'Grey/Red'],
    featured: false,
  },

  // ═══════════════════════════════════════
  //  JORDAN (4 new products)
  // ═══════════════════════════════════════
  {
    name: 'Air Jordan 4 Retro',
    brand: 'Jordan',
    category: 'Lifestyle',
    gender: 'Unisex',
    price: 210,
    oldPrice: 210,
    discount: 0,
    rating: 4.9,
    reviewCount: 541,
    image: 'https://images.unsplash.com/photo-1556048219-bb6978360b84?w=600&q=80',
    description: "One of the most iconic silhouettes in sneaker history, the Air Jordan 4 Retro features visible Air cushioning, mesh netting on the upper panels, and a plastic wing eyelet — all reimagined in premium materials for today's collector.",
    stock: 20,
    sizes: [7, 8, 9, 10, 11, 12],
    colors: ['White Cement', 'Military Black', 'Fire Red'],
    featured: true,
  },
  {
    name: 'Air Jordan 3 Retro',
    brand: 'Jordan',
    category: 'Lifestyle',
    gender: 'Unisex',
    price: 200,
    oldPrice: 200,
    discount: 0,
    rating: 4.9,
    reviewCount: 478,
    image: 'https://images.unsplash.com/photo-1607522370275-f14206abe5d3?w=600&q=80',
    description: "The Air Jordan 3 Retro introduced the iconic elephant print and the first visible Air unit in the Jordan line. Designed by Tinker Hatfield, this classic features a tumbled leather upper and a cement-patterned outsole.",
    stock: 18,
    sizes: [7, 8, 9, 10, 11, 12],
    colors: ['White Cement', 'True Blue', 'Black Cement'],
    featured: true,
  },
  {
    name: 'Air Jordan 11 Retro Low',
    brand: 'Jordan',
    category: 'Lifestyle',
    gender: 'Men',
    price: 185,
    oldPrice: 185,
    discount: 0,
    rating: 4.8,
    reviewCount: 312,
    image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&q=80',
    description: "The Air Jordan 11 Retro Low features the iconic patent leather mudguard and full-length Air sole unit in a lower profile. A sleeker take on one of the most beloved Jordans ever made, perfect for everyday wear.",
    stock: 15,
    sizes: [7, 8, 9, 10, 11, 12, 13],
    colors: ['Concord Black/White', 'Bred', 'Columbia Blue/White'],
    featured: false,
  },
  {
    name: 'Air Jordan 6 Retro',
    brand: 'Jordan',
    category: 'Basketball',
    gender: 'Men',
    price: 200,
    oldPrice: 200,
    discount: 0,
    rating: 4.8,
    reviewCount: 267,
    image: 'https://images.unsplash.com/photo-1600185365483-26d7a4cc7519?w=600&q=80',
    description: "The shoe MJ wore when he won his first NBA championship in 1991. The Air Jordan 6 Retro features a rubber tongue tab, lace locks, and a molded heel counter for support — now available in iconic retro colorways.",
    stock: 14,
    sizes: [8, 9, 10, 11, 12, 13],
    colors: ['Carmine Red/White', 'Infrared Black', 'Midnight Navy'],
    featured: false,
  },

  // ═══════════════════════════════════════
  //  VANS (4 new products)
  // ═══════════════════════════════════════
  {
    name: 'Vans Authentic',
    brand: 'Vans',
    category: 'Lifestyle',
    gender: 'Unisex',
    price: 55,
    oldPrice: 55,
    discount: 0,
    rating: 4.7,
    reviewCount: 634,
    image: 'https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?w=600&q=80',
    description: "The Vans Authentic is the original skate shoe — first made in 1966 and still going strong. Low profile canvas upper, signature waffle outsole, and metal eyelets. Simple, clean, and timeless.",
    stock: 90,
    sizes: [5, 6, 7, 8, 9, 10, 11, 12],
    colors: ['Black/White', 'True White', 'Checkerboard Black/White'],
    featured: true,
  },
  {
    name: 'Vans Sk8-Hi',
    brand: 'Vans',
    category: 'Skateboarding',
    gender: 'Unisex',
    price: 75,
    oldPrice: 75,
    discount: 0,
    rating: 4.8,
    reviewCount: 489,
    image: 'https://images.unsplash.com/photo-1463100099107-aa0980c362e6?w=600&q=80',
    description: "The Vans Sk8-Hi is a high-top icon that's been shredding since 1978. Padded collar for ankle support, signature side stripe, and a grippy waffle outsole make it as functional on the board as it is stylish off it.",
    stock: 65,
    sizes: [5, 6, 7, 8, 9, 10, 11, 12],
    colors: ['Black/White', 'True White', 'Navy/White'],
    featured: true,
  },
  {
    name: 'Vans Era',
    brand: 'Vans',
    category: 'Skateboarding',
    gender: 'Unisex',
    price: 60,
    oldPrice: 60,
    discount: 0,
    rating: 4.6,
    reviewCount: 312,
    image: 'https://images.unsplash.com/photo-1512374382149-233c42b6a83b?w=600&q=80',
    description: "Co-designed with pro skaters Tony Alva and Stacy Peralta in 1976, the Vans Era features a padded collar for comfort, double-stitched canvas upper for durability, and the classic waffle rubber outsole.",
    stock: 70,
    sizes: [6, 7, 8, 9, 10, 11, 12],
    colors: ['Black/Black', 'White/White', 'Navy/White'],
    featured: false,
  },
  {
    name: 'Vans Slip-On Pro',
    brand: 'Vans',
    category: 'Skateboarding',
    gender: 'Unisex',
    price: 70,
    oldPrice: 70,
    discount: 0,
    rating: 4.5,
    reviewCount: 198,
    image: 'https://images.unsplash.com/photo-1584735175315-9d5df23be620?w=600&q=80',
    description: "The Vans Slip-On Pro is the laceless classic, built for skateboarding with Sickstick rubber outsole for grip, UltraCush HD insole for impact protection, and a Duracap-reinforced upper for extra durability.",
    stock: 45,
    sizes: [6, 7, 8, 9, 10, 11, 12],
    colors: ['Black/White', 'Checkerboard', 'White/Gum'],
    featured: false,
  },

  // ═══════════════════════════════════════
  //  HOKA (5 new products)
  // ═══════════════════════════════════════
  {
    name: 'Hoka Clifton 9',
    brand: 'Hoka',
    category: 'Running',
    gender: 'Unisex',
    price: 145,
    oldPrice: 145,
    discount: 0,
    rating: 4.8,
    reviewCount: 387,
    image: 'https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?w=600&q=80',
    description: "The Hoka Clifton 9 is one of the most comfortable everyday trainers ever made. Lightweight compression-molded EVA midsole with a meta-rocker geometry creates a smooth, effortless stride from heel to toe.",
    stock: 35,
    sizes: [7, 8, 9, 10, 11, 12],
    colors: ['White/Ice Water', 'Black/Black', 'Cyclamen/Peach'],
    featured: true,
  },
  {
    name: 'Hoka Bondi 8',
    brand: 'Hoka',
    category: 'Running',
    gender: 'Unisex',
    price: 165,
    oldPrice: 165,
    discount: 0,
    rating: 4.7,
    reviewCount: 298,
    image: 'https://images.unsplash.com/photo-1608231387042-66d1773070a5?w=600&q=80',
    description: "Hoka's most cushioned road shoe, the Bondi 8 features an ultra-thick EVA midsole that absorbs impact on even the hardest surfaces. A plush interior and wide forefoot make it the go-to shoe for recovery runs.",
    stock: 28,
    sizes: [7, 8, 9, 10, 11, 12],
    colors: ['Shifting Sand/Eggnog', 'Black/Black', 'Blue Graphite/Illusion'],
    featured: false,
  },
  {
    name: 'Hoka Speedgoat 5',
    brand: 'Hoka',
    category: 'Running',
    gender: 'Unisex',
    price: 155,
    oldPrice: 155,
    discount: 0,
    rating: 4.8,
    reviewCount: 213,
    image: 'https://images.unsplash.com/photo-1460353581641-37baddab0fa2?w=600&q=80',
    description: "Named after ultra-trail legend Karl Meltzer, the Hoka Speedgoat 5 is built for rugged terrain. Vibram® Megagrip outsole with 5mm lugs tackles technical trails, while a wide midsole provides maximum stability on uneven ground.",
    stock: 22,
    sizes: [7, 8, 9, 10, 11, 12],
    colors: ['Evening Primrose/Camellia', 'Black/Castlerock', 'Thyme/Radiant Yellow'],
    featured: false,
  },
  {
    name: 'Hoka Mach 6',
    brand: 'Hoka',
    category: 'Running',
    gender: 'Unisex',
    price: 145,
    oldPrice: 145,
    discount: 0,
    rating: 4.7,
    reviewCount: 176,
    image: 'https://images.unsplash.com/photo-1571601624534-986ef2f10d21?w=600&q=80',
    description: "The Hoka Mach 6 is a lightweight daily trainer with a responsive CMEVA midsole that rewards faster paces. A mesh upper keeps feet cool during tempo runs, and the early stage meta-rocker promotes quick turnover.",
    stock: 30,
    sizes: [7, 8, 9, 10, 11, 12],
    colors: ['Bellwether Blue/Swim Day', 'Black/Black', 'Coral/Peach'],
    featured: false,
  },
  {
    name: 'Hoka Cielo X1',
    brand: 'Hoka',
    category: 'Performance',
    gender: 'Unisex',
    price: 250,
    oldPrice: 250,
    discount: 0,
    rating: 4.8,
    reviewCount: 48,
    image: 'https://images.unsplash.com/photo-1539185441755-769473a23570?w=600&q=80',
    description: "Hoka's most advanced race-day shoe features a PEBA-based foam midsole and full-length carbon fiber plate for maximum energy return. Developed in partnership with elite athletes for sub-elite and professional marathoners.",
    stock: 8,
    sizes: [7, 8, 9, 10, 11],
    colors: ['Blanc De Blanc/Illusion', 'Black/Solar Eclipse', 'Solar Flare/Squash'],
    featured: true,
  },

  // ═══════════════════════════════════════
  //  ON RUNNING (5 new products)
  // ═══════════════════════════════════════
  {
    name: 'On Cloudmonster 2',
    brand: 'On Running',
    category: 'Running',
    gender: 'Unisex',
    price: 170,
    oldPrice: 170,
    discount: 0,
    rating: 4.8,
    reviewCount: 234,
    image: 'https://images.unsplash.com/photo-1587563871167-1ee9c731aefb?w=600&q=80',
    description: "The On Cloudmonster 2 features oversized CloudTec® pods that compress on impact and slingshot you forward. A rocker profile and Helion™ superfoam midsole make this On's most explosive everyday trainer yet.",
    stock: 25,
    sizes: [7, 8, 9, 10, 11, 12],
    colors: ['Undyed/White', 'Black/Eclipse', 'Hay/Flame'],
    featured: true,
  },
  {
    name: 'On Cloud X 4',
    brand: 'On Running',
    category: 'Training',
    gender: 'Unisex',
    price: 150,
    oldPrice: 150,
    discount: 0,
    rating: 4.7,
    reviewCount: 198,
    image: 'https://images.unsplash.com/photo-1605348532760-6753d2c43329?w=600&q=80',
    description: "The On Cloud X 4 is a do-everything trainer for gym sessions, HIIT, and light runs. CloudTec® cushioning adapts to your movement, while a reinforced midfoot cage provides lateral stability for multi-directional workouts.",
    stock: 30,
    sizes: [6, 7, 8, 9, 10, 11, 12],
    colors: ['White/Black', 'Black/White', 'Rose/White'],
    featured: false,
  },
  {
    name: 'On Cloudflow 4',
    brand: 'On Running',
    category: 'Running',
    gender: 'Unisex',
    price: 150,
    oldPrice: 150,
    discount: 0,
    rating: 4.7,
    reviewCount: 167,
    image: 'https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?w=600&q=80',
    description: "Built for tempo runs and races, the On Cloudflow 4 is engineered for speed and efficiency. The lightweight Helion foam and dual-density CloudTec® outsole provide a snappy, responsive ride that rewards faster paces.",
    stock: 20,
    sizes: [7, 8, 9, 10, 11, 12],
    colors: ['Indigo/Copper', 'Black/Eclipse', 'Ivory/Cobalt'],
    featured: false,
  },
  {
    name: 'On Cloudnova',
    brand: 'On Running',
    category: 'Lifestyle',
    gender: 'Unisex',
    price: 150,
    oldPrice: 150,
    discount: 0,
    rating: 4.6,
    reviewCount: 289,
    image: 'https://images.unsplash.com/photo-1588361035994-295e21daa761?w=600&q=80',
    description: "Where performance meets style — the On Cloudnova features a chunky CloudTec® sole and a premium knit upper that make it as wearable as a lifestyle sneaker. Cushioned and bold, it's the everyday shoe for the modern athlete.",
    stock: 35,
    sizes: [6, 7, 8, 9, 10, 11, 12],
    colors: ['White/Flame', 'Black/Eclipse', 'Mineral/Aloe'],
    featured: true,
  },
  {
    name: 'On Cloudracer 3',
    brand: 'On Running',
    category: 'Performance',
    gender: 'Unisex',
    price: 200,
    oldPrice: 200,
    discount: 0,
    rating: 4.8,
    reviewCount: 62,
    image: 'https://images.unsplash.com/photo-1608379743498-61f93498f0e9?w=600&q=80',
    description: "On's elite racing flat features a carbon fiber plate embedded in Helion HF foam — the brand's highest energy-return compound. The speed-lacing system saves seconds, and the aerodynamic upper sheds weight mile after mile.",
    stock: 10,
    sizes: [7, 8, 9, 10, 11],
    colors: ['Ice/White', 'Black/Midnight', 'Flame/White'],
    featured: false,
  },

  // ═══════════════════════════════════════
  //  SAUCONY (4 new products)
  // ═══════════════════════════════════════
  {
    name: 'Saucony Kinvara 14',
    brand: 'Saucony',
    category: 'Running',
    gender: 'Unisex',
    price: 110,
    oldPrice: 110,
    discount: 0,
    rating: 4.7,
    reviewCount: 213,
    image: 'https://images.unsplash.com/photo-1460353581641-37baddab0fa2?w=600&q=80',
    description: "The Saucony Kinvara 14 is the lightweight speedster that started a revolution. PWRRUN foam midsole delivers an energetic ride, while the thin outsole and low heel drop encourage a natural, efficient running form.",
    stock: 28,
    sizes: [7, 8, 9, 10, 11, 12],
    colors: ['Spearmint/Acid', 'Black/Quartz', 'White/Blue'],
    featured: false,
  },
  {
    name: 'Saucony Ride 17',
    brand: 'Saucony',
    category: 'Running',
    gender: 'Unisex',
    price: 140,
    oldPrice: 140,
    discount: 0,
    rating: 4.8,
    reviewCount: 278,
    image: 'https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?w=600&q=80',
    description: "A perennial favorite among everyday runners, the Saucony Ride 17 offers a smooth, cushioned ride with PWRRUN midsole foam. The FORMFIT collar wraps your ankle for a secure, personalized fit on every run.",
    stock: 32,
    sizes: [7, 8, 9, 10, 11, 12],
    colors: ['Orchid/Shadow', 'Black/Slime', 'White/Silver'],
    featured: true,
  },
  {
    name: 'Saucony Endorphin Speed 4',
    brand: 'Saucony',
    category: 'Running',
    gender: 'Unisex',
    price: 170,
    oldPrice: 170,
    discount: 0,
    rating: 4.9,
    reviewCount: 145,
    image: 'https://images.unsplash.com/photo-1608231387042-66d1773070a5?w=600&q=80',
    description: "The Saucony Endorphin Speed 4 pairs a nylon plate with PWRRUN PB foam for a propulsive, race-ready feel without the stiff carbon plate. Ideal for tempo workouts and race-day use, it's the versatile speedster in Saucony's lineup.",
    stock: 20,
    sizes: [7, 8, 9, 10, 11],
    colors: ['Citrus/Black', 'White/Prospect', 'Acid/Shadow'],
    featured: true,
  },
  {
    name: 'Saucony Jazz Original',
    brand: 'Saucony',
    category: 'Lifestyle',
    gender: 'Unisex',
    price: 80,
    oldPrice: 80,
    discount: 0,
    rating: 4.6,
    reviewCount: 189,
    image: 'https://images.unsplash.com/photo-1556906781-9a414e2a9c86?w=600&q=80',
    description: "A retro icon since 1981, the Saucony Jazz Original features a suede and nylon upper, tri-color outsole, and vintage runner styling. Its five-eyelet lacing and EVA midsole make it as comfortable as it is nostalgic.",
    stock: 40,
    sizes: [6, 7, 8, 9, 10, 11, 12],
    colors: ['Silver/Royal', 'White/Navy/Red', 'Black/Blue'],
    featured: false,
  },

  // ═══════════════════════════════════════
  //  SALOMON (4 new products)
  // ═══════════════════════════════════════
  {
    name: 'Salomon Speedcross 6',
    brand: 'Salomon',
    category: 'Running',
    gender: 'Unisex',
    price: 140,
    oldPrice: 140,
    discount: 0,
    rating: 4.8,
    reviewCount: 312,
    image: 'https://images.unsplash.com/photo-1571601624534-986ef2f10d21?w=600&q=80',
    description: "The Salomon Speedcross 6 is the definitive off-road running shoe. Its aggressive chevron lugs bite into soft, technical terrain with unmatched grip, while the Quicklace™ system lets you tighten up in seconds before the start gun fires.",
    stock: 25,
    sizes: [7, 8, 9, 10, 11, 12],
    colors: ['Black/Black/Phantom', 'Fiery Red/Black', 'Surf Web/White'],
    featured: true,
  },
  {
    name: 'Salomon XT-6',
    brand: 'Salomon',
    category: 'Lifestyle',
    gender: 'Unisex',
    price: 200,
    oldPrice: 200,
    discount: 0,
    rating: 4.9,
    reviewCount: 267,
    image: 'https://images.unsplash.com/photo-1582588678413-dbf45f4823e9?w=600&q=80',
    description: "Originally a trail racing shoe, the Salomon XT-6 has become a streetwear grail thanks to its aggressive silhouette and technical detailing. The Quicklace™ system, Contragrip® outsole, and woven Sensifit upper make it unmistakable.",
    stock: 15,
    sizes: [7, 8, 9, 10, 11, 12],
    colors: ['Black/Black/Phantom', 'Vanilla Ice/Almond Milk', 'Blue Graphite/Lunar Rock'],
    featured: true,
  },
  {
    name: 'Salomon Ultra Glide 2',
    brand: 'Salomon',
    category: 'Running',
    gender: 'Unisex',
    price: 145,
    oldPrice: 145,
    discount: 0,
    rating: 4.7,
    reviewCount: 134,
    image: 'https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?w=600&q=80',
    description: "The Salomon Ultra Glide 2 bridges trail performance and road comfort. EnergyCell+ foam provides a cushioned, bouncy ride on gravel and packed trails, while a Contagrip® outsole handles varying terrain with confidence.",
    stock: 18,
    sizes: [7, 8, 9, 10, 11, 12],
    colors: ['Black/Ebony/White', 'Peacock Blue/Black', 'Plum Cassis/Black'],
    featured: false,
  },
  {
    name: 'Salomon ACS Pro Advanced',
    brand: 'Salomon',
    category: 'Lifestyle',
    gender: 'Unisex',
    price: 220,
    oldPrice: 220,
    discount: 0,
    rating: 4.7,
    reviewCount: 89,
    image: 'https://images.unsplash.com/photo-1520256862855-398228c41684?w=600&q=80',
    description: "The Salomon ACS Pro Advanced pushes the boundaries of outdoor footwear design. A sleek, futuristic silhouette combines with Contragrip® outsole technology and a premium woven upper for a shoe that bridges the gap between sport and fashion.",
    stock: 12,
    sizes: [7, 8, 9, 10, 11, 12],
    colors: ['Black/Transparent', 'Glacier Gray/White', 'Arctic Ice/Black'],
    featured: false,
  },

  // ═══════════════════════════════════════
  //  ASICS (additional products)
  // ═══════════════════════════════════════
  {
    name: 'Asics Gel-Nimbus 26',
    brand: 'Asics',
    category: 'Running',
    gender: 'Unisex',
    price: 160,
    oldPrice: 160,
    discount: 0,
    rating: 4.8,
    reviewCount: 289,
    image: 'https://images.unsplash.com/photo-1539185441755-769473a23570?w=600&q=80',
    description: "The Asics Gel-Nimbus 26 is a premium daily trainer built for long-distance comfort. FF Blast+ Eco foam and a GEL™ technology unit in the heel absorb shock on every landing, while the engineered knit upper adapts to your foot shape.",
    stock: 28,
    sizes: [7, 8, 9, 10, 11, 12],
    colors: ['White/Blue', 'Black/Graphite Grey', 'Lilac Opal/Violet'],
    featured: true,
  },
  {
    name: 'Asics Gel-Kayano 31',
    brand: 'Asics',
    category: 'Running',
    gender: 'Unisex',
    price: 160,
    oldPrice: 160,
    discount: 0,
    rating: 4.7,
    reviewCount: 214,
    image: 'https://images.unsplash.com/photo-1582588678413-dbf45f4823e9?w=600&q=80',
    description: "The Asics Gel-Kayano 31 is the gold standard for overpronation support. A 4D Guidance System and dual-density foam guide each footstrike into alignment, while GEL™ cushioning absorbs impact on long, demanding runs.",
    stock: 22,
    sizes: [7, 8, 9, 10, 11, 12],
    colors: ['Black/Graphite Grey', 'White/Blue', 'Thunder Blue/Pale Blue'],
    featured: false,
  },
  {
    name: 'Asics Gel-Lyte III OG',
    brand: 'Asics',
    category: 'Lifestyle',
    gender: 'Unisex',
    price: 100,
    oldPrice: 100,
    discount: 0,
    rating: 4.7,
    reviewCount: 178,
    image: 'https://images.unsplash.com/photo-1556906781-9a414e2a9c86?w=600&q=80',
    description: "The Asics Gel-Lyte III OG is a retro runner cult classic known for its split tongue design — a Tomo Kihachi innovation from 1990. Premium suede and mesh construction with a GEL™ unit make it a lifestyle staple.",
    stock: 30,
    sizes: [6, 7, 8, 9, 10, 11, 12],
    colors: ['Birch/Gull Grey', 'Black/Black', 'Burgundy/Cream'],
    featured: false,
  },
  {
    name: 'Asics Novablast 4',
    brand: 'Asics',
    category: 'Running',
    gender: 'Unisex',
    price: 130,
    oldPrice: 130,
    discount: 0,
    rating: 4.8,
    reviewCount: 198,
    image: 'https://images.unsplash.com/photo-1571601624534-986ef2f10d21?w=600&q=80',
    description: "The bounciest shoe in Asics' lineup, the Novablast 4 features a trampoline-like FF Blast+ midsole that delivers an explosive toe-off. The new vertical geometry adds even more height and spring underfoot for an exhilarating everyday run.",
    stock: 26,
    sizes: [7, 8, 9, 10, 11, 12],
    colors: ['White/Aquamarine', 'Black/Graphite Grey', 'Papaya/Sunrise Red'],
    featured: true,
  },

  // ═══════════════════════════════════════
  //  NIKE — additional products
  // ═══════════════════════════════════════
  {
    name: 'Nike Free RN 5.0 Next Nature',
    brand: 'Nike',
    category: 'Running',
    gender: 'Unisex',
    price: 100,
    oldPrice: 100,
    discount: 0,
    rating: 4.6,
    reviewCount: 134,
    image: 'https://images.unsplash.com/photo-1600185365483-26d7a4cc7519?w=600&q=80',
    description: "The Nike Free RN 5.0 Next Nature features a segmented outsole that flexes with your foot for a natural feel. Made with at least 20% recycled materials by weight, it's designed to reduce environmental impact without sacrificing performance.",
    stock: 35,
    sizes: [6, 7, 8, 9, 10, 11, 12],
    colors: ['White/Pure Platinum', 'Black/Anthracite', 'Coral/Pink'],
    featured: false,
  },
  {
    name: 'Nike Air Max 97',
    brand: 'Nike',
    category: 'Lifestyle',
    gender: 'Unisex',
    price: 175,
    oldPrice: 175,
    discount: 0,
    rating: 4.8,
    reviewCount: 412,
    image: 'https://images.unsplash.com/photo-1549298916-b41d501d3772?w=600&q=80',
    description: "Inspired by bullet trains, the Nike Air Max 97 features full-length visible Air cushioning and a sleek ripple design across the upper. A true icon of late-90s design that remains as fresh and desirable as ever.",
    stock: 20,
    sizes: [7, 8, 9, 10, 11, 12],
    colors: ['Silver Bullet', 'Black/Gold', 'White/Blue'],
    featured: true,
  },
  {
    name: 'Nike Pegasus 41',
    brand: 'Nike',
    category: 'Running',
    gender: 'Unisex',
    price: 130,
    oldPrice: 130,
    discount: 0,
    rating: 4.8,
    reviewCount: 521,
    image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&q=80',
    description: "The Nike Pegasus 41 is one of the world's best-selling running shoes for good reason. React foam delivers a smooth, responsive ride, while a wider forefoot and breathable mesh upper make it a reliable daily companion for any runner.",
    stock: 50,
    sizes: [6, 7, 8, 9, 10, 11, 12],
    colors: ['Blue/White', 'Black/Anthracite', 'Photon Dust/Pink'],
    featured: true,
  },

  // ═══════════════════════════════════════
  //  ADIDAS — additional products
  // ═══════════════════════════════════════
  {
    name: 'Adidas Samba OG',
    brand: 'Adidas',
    category: 'Lifestyle',
    gender: 'Unisex',
    price: 100,
    oldPrice: 100,
    discount: 0,
    rating: 4.9,
    reviewCount: 678,
    image: 'https://images.unsplash.com/photo-1491553895911-0055eca6402d?w=600&q=80',
    description: "Originally designed for icy football pitches in 1950, the Adidas Samba OG has become the It shoe of the decade. Premium leather upper, suede T-toe overlay, and a distinctive gum rubber outsole define this timeless icon.",
    stock: 45,
    sizes: [6, 7, 8, 9, 10, 11, 12],
    colors: ['Core Black/White/Gum', 'Cloud White/Core Black/Gum', 'Shadow Navy/Cloud White'],
    featured: true,
  },
  {
    name: 'Adidas Terrex Free Hiker 2',
    brand: 'Adidas',
    category: 'Running',
    gender: 'Unisex',
    price: 200,
    oldPrice: 200,
    discount: 0,
    rating: 4.7,
    reviewCount: 98,
    image: 'https://images.unsplash.com/photo-1605408499391-6368c628ef42?w=600&q=80',
    description: "The Adidas Terrex Free Hiker 2 bridges trail running and hiking with a BOOST midsole for all-day comfort and a Continental™ Rubber outsole for reliable grip on wet and rocky terrain. Built for multi-day adventures.",
    stock: 18,
    sizes: [7, 8, 9, 10, 11, 12],
    colors: ['Wonder Steel/Grey', 'Core Black/Carbon', 'Blue Rush/Pulse Olive'],
    featured: false,
  },
  {
    name: 'Adidas Handball Spezial',
    brand: 'Adidas',
    category: 'Lifestyle',
    gender: 'Unisex',
    price: 110,
    oldPrice: 110,
    discount: 0,
    rating: 4.8,
    reviewCount: 345,
    image: 'https://images.unsplash.com/photo-1588361035994-295e21daa761?w=600&q=80',
    description: "A handball shoe from the 70s reimagined for today, the Adidas Handball Spezial features premium suede upper, gum rubber outsole, and signature 3-Stripes. Its slim, low-profile silhouette has made it a global streetwear phenomenon.",
    stock: 38,
    sizes: [6, 7, 8, 9, 10, 11, 12],
    colors: ['Brown/Ecru', 'Collegiate Green/White', 'Core Black/White'],
    featured: true,
  },

  // ═══════════════════════════════════════
  //  NEW BALANCE — additional products
  // ═══════════════════════════════════════
  {
    name: 'New Balance 1906R',
    brand: 'New Balance',
    category: 'Lifestyle',
    gender: 'Unisex',
    price: 150,
    oldPrice: 150,
    discount: 0,
    rating: 4.8,
    reviewCount: 289,
    image: 'https://images.unsplash.com/photo-1520256862855-398228c41684?w=600&q=80',
    description: "The New Balance 1906R is a dad sneaker with performance DNA. Derived from the 1906 running shoe, it features a full-length N-ergy midsole, reflective details, and a premium multilayer upper that blends function and futuristic fashion.",
    stock: 30,
    sizes: [6, 7, 8, 9, 10, 11, 12],
    colors: ['Silver/White', 'Black/Gunmetal', 'Magnet/Aluminum'],
    featured: true,
  },
  {
    name: 'New Balance SC Trainer v2',
    brand: 'New Balance',
    category: 'Training',
    gender: 'Unisex',
    price: 155,
    oldPrice: 155,
    discount: 0,
    rating: 4.7,
    reviewCount: 112,
    image: 'https://images.unsplash.com/photo-1582588678413-dbf45f4823e9?w=600&q=80',
    description: "The New Balance SC Trainer v2 brings race-day energy to the gym. FuelCell foam and a carbon fiber plate make plyometrics and sled pushes feel effortless, while a wide, stable base grounds you during strength work.",
    stock: 16,
    sizes: [7, 8, 9, 10, 11, 12],
    colors: ['Black/Gold', 'White/Blue', 'Team Red/White'],
    featured: false,
  },

  // ═══════════════════════════════════════
  //  PUMA — additional products
  // ═══════════════════════════════════════
  {
    name: 'Puma Speedcat OG',
    brand: 'Puma',
    category: 'Lifestyle',
    gender: 'Unisex',
    price: 100,
    oldPrice: 100,
    discount: 0,
    rating: 4.7,
    reviewCount: 234,
    image: 'https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=600&q=80',
    description: "Originally made for motorsport drivers in the pits, the Puma Speedcat OG has crossed over into streetwear as one of the season's most coveted silhouettes. Ultra-slim profile, suede upper, and that iconic racing-inspired look.",
    stock: 35,
    sizes: [6, 7, 8, 9, 10, 11, 12],
    colors: ['Puma Black/Puma White', 'Intense Red/Puma White', 'Powder Puff/Gold'],
    featured: true,
  },
  {
    name: 'Puma Deviate NITRO Elite 3',
    brand: 'Puma',
    category: 'Performance',
    gender: 'Unisex',
    price: 225,
    oldPrice: 225,
    discount: 0,
    rating: 4.8,
    reviewCount: 56,
    image: 'https://images.unsplash.com/photo-1608379743498-61f93498f0e9?w=600&q=80',
    description: "Puma's race-day workhorse, the Deviate NITRO Elite 3, features a NITRO Elite foam midsole and full-length carbon fiber plate that propels you forward at speed. Designed for personal bests on any road race distance.",
    stock: 8,
    sizes: [7, 8, 9, 10, 11],
    colors: ['Electric Lime/Black', 'Ultra Blue/White', 'White/Gold'],
    featured: false,
  },

  // ═══════════════════════════════════════
  //  REEBOK — additional products
  // ═══════════════════════════════════════
  {
    name: 'Reebok Question Mid',
    brand: 'Reebok',
    category: 'Basketball',
    gender: 'Men',
    price: 130,
    oldPrice: 130,
    discount: 0,
    rating: 4.7,
    reviewCount: 178,
    image: 'https://images.unsplash.com/photo-1562183241-840b8af0721e?w=600&q=80',
    description: "Allen Iverson's first signature shoe, the Reebok Question Mid is a basketball icon. The hexagonal DMX cushioning system, leather upper, and classic Union Jack tongue logo make it a collector's staple with serious on-court credentials.",
    stock: 16,
    sizes: [7, 8, 9, 10, 11, 12, 13],
    colors: ['White/Royal Blue', 'Black/Gold', 'Red/White'],
    featured: true,
  },

  // ═══════════════════════════════════════
  //  UNDER ARMOUR — additional products
  // ═══════════════════════════════════════
  {
    name: 'Under Armour HOVR Phantom 3',
    brand: 'Under Armour',
    category: 'Running',
    gender: 'Unisex',
    price: 140,
    oldPrice: 140,
    discount: 0,
    rating: 4.7,
    reviewCount: 198,
    image: 'https://images.unsplash.com/photo-1587563871167-1ee9c731aefb?w=600&q=80',
    description: "The UA HOVR Phantom 3 features a HOVR foam midsole that provides 'zero gravity feel' cushioning. Connected technology tracks your run metrics via the MapMyRun app, offering real-time coaching and cadence feedback.",
    stock: 22,
    sizes: [7, 8, 9, 10, 11, 12],
    colors: ['Black/Black', 'White/Blue', 'Red/Black'],
    featured: false,
  },
  {
    name: 'Under Armour SlipSpeed Mega',
    brand: 'Under Armour',
    category: 'Training',
    gender: 'Men',
    price: 120,
    oldPrice: 120,
    discount: 0,
    rating: 4.6,
    reviewCount: 134,
    image: 'https://images.unsplash.com/photo-1608379743498-61f93498f0e9?w=600&q=80',
    description: "The UA SlipSpeed Mega features an innovative fold-down heel that converts the shoe from a lace-up trainer to a slip-on recovery shoe. HOVR foam cushioning adapts to both gym floors and casual street wear.",
    stock: 18,
    sizes: [7, 8, 9, 10, 11, 12],
    colors: ['Black/Gold', 'White/Red', 'Grey/Blue'],
    featured: false,
  },

  // ═══════════════════════════════════════
  //  CONVERSE — additional products
  // ═══════════════════════════════════════
  {
    name: 'Converse Jack Purcell',
    brand: 'Converse',
    category: 'Lifestyle',
    gender: 'Unisex',
    price: 70,
    oldPrice: 70,
    discount: 0,
    rating: 4.7,
    reviewCount: 267,
    image: 'https://images.unsplash.com/photo-1494496195158-c3bc1aca6533?w=600&q=80',
    description: "Originally designed for badminton in the 1930s, the Converse Jack Purcell is defined by its signature 'smile' toe cap. Premium canvas or leather upper and vulcanized rubber outsole make it a refined alternative to the Chuck Taylor.",
    stock: 45,
    sizes: [6, 7, 8, 9, 10, 11, 12],
    colors: ['White/Black', 'Egret/Light Silver', 'Black/White'],
    featured: false,
  },

  // ═══════════════════════════════════════
  //  NIKE — additional products
  // ═══════════════════════════════════════
  {
    name: 'Nike Air Max Plus',
    brand: 'Nike',
    category: 'Lifestyle',
    gender: 'Men',
    price: 185,
    oldPrice: 185,
    discount: 0,
    rating: 4.7,
    reviewCount: 334,
    image: 'https://images.unsplash.com/photo-1556048219-bb6978360b84?w=600&q=80',
    description: "Inspired by palm trees, ocean waves, and the Miami sunset, the Nike Air Max Plus (TN) features a distinctive gradient upper with tuned Air units for a smooth, cushioned ride. A street cult classic since 1998.",
    stock: 24,
    sizes: [7, 8, 9, 10, 11, 12],
    colors: ['Black/Anthracite/Volt', 'White/White/Platinum', 'Hyper Blue/White'],
    featured: false,
  },
  {
    name: 'Nike Ja 2',
    brand: 'Nike',
    category: 'Basketball',
    gender: 'Men',
    price: 110,
    oldPrice: 110,
    discount: 0,
    rating: 4.7,
    reviewCount: 156,
    image: 'https://images.unsplash.com/photo-1600185365483-26d7a4cc7519?w=600&q=80',
    description: "Ja Morant's second signature shoe is built for explosive, fast-paced guards. A lightweight React foam midsole with a Zoom Air unit in the forefoot provides fast energy return, while a chevron outsole grips the court through sharp cuts.",
    stock: 20,
    sizes: [7, 8, 9, 10, 11, 12],
    colors: ['Black/Silver', 'White/University Blue', 'Midnight Navy/Volt'],
    featured: false,
  },

  // ═══════════════════════════════════════
  //  ADIDAS — additional products
  // ═══════════════════════════════════════
  {
    name: 'Adidas Adistar CS',
    brand: 'Adidas',
    category: 'Running',
    gender: 'Unisex',
    price: 130,
    oldPrice: 130,
    discount: 0,
    rating: 4.6,
    reviewCount: 143,
    image: 'https://images.unsplash.com/photo-1514989940723-e8e51635b782?w=600&q=80',
    description: "The Adidas Adistar CS is engineered for comfortable, long-distance road running. Dual-density Lightstrike Pro foam cushions impact while guiding the foot to a more efficient stride, ideal for high-mileage training weeks.",
    stock: 20,
    sizes: [7, 8, 9, 10, 11, 12],
    colors: ['Cloud White/Core Black', 'Solar Red/White', 'Wonder Blue/Silver'],
    featured: false,
  },

  // ═══════════════════════════════════════
  //  PUMA — additional products
  // ═══════════════════════════════════════
  {
    name: 'Saucony Shadow 6000',
    brand: 'Saucony',
    category: 'Lifestyle',
    gender: 'Unisex',
    price: 110,
    oldPrice: 110,
    discount: 0,
    rating: 4.7,
    reviewCount: 156,
    image: 'https://images.unsplash.com/photo-1557861671-4c6eb27bfe5b?w=600&q=80',
    description: "The Saucony Shadow 6000 is a premium retro runner with roots in the 1980s. Suede and mesh upper in bold color-blocking, EVA midsole with GRID cushioning, and an outsole inspired by high-performance trail shoes of the era.",
    stock: 30,
    sizes: [6, 7, 8, 9, 10, 11, 12],
    colors: ['Forest/Gum', 'Black/Silver', 'White/Navy/Red'],
    featured: false,
  },
  {
    name: 'Puma Pacer Future Knit',
    brand: 'Puma',
    category: 'Lifestyle',
    gender: 'Unisex',
    price: 75,
    oldPrice: 90,
    discount: 17,
    rating: 4.5,
    reviewCount: 112,
    image: 'https://images.unsplash.com/photo-1571601624534-986ef2f10d21?w=600&q=80',
    description: "The Puma Pacer Future Knit pairs a stretchy knit upper with a chunky EVA midsole for all-day comfort. Clean lines and a minimalist design make it a versatile everyday shoe that transitions effortlessly from gym to street.",
    stock: 40,
    sizes: [6, 7, 8, 9, 10, 11, 12],
    colors: ['White/Silver', 'Black/Dark Shadow', 'Navy/White'],
    featured: false,
  },

];

async function seedProducts() {
  try {
    const count = await Product.countDocuments();
    if (count > 0) {
      console.log(`⚠️  Database already has ${count} products. Clearing for re-seed...`);
      await Product.deleteMany({});
      console.log('🗑️  All existing products removed');
    }

    const inserted = await Product.insertMany(products);
    console.log(`\n✅ Successfully inserted ${inserted.length} products into MongoDB!\n`);

    const brands = [...new Set(products.map(p => p.brand))];
    console.log('📊 Summary by Brand:');
    for (const brand of brands) {
      const c = products.filter(p => p.brand === brand).length;
      console.log(`   ${brand.padEnd(22)} → ${c} products`);
    }

    const genders = ['Men', 'Women', 'Unisex'];
    console.log('\n👟 Summary by Gender:');
    for (const g of genders) {
      const c = products.filter(p => p.gender === g).length;
      console.log(`   ${g.padEnd(22)} → ${c} products`);
    }

    const categories = [...new Set(products.map(p => p.category))];
    console.log('\n🏷️  Summary by Category:');
    for (const cat of categories) {
      const c = products.filter(p => p.category === cat).length;
      console.log(`   ${cat.padEnd(22)} → ${c} products`);
    }

    console.log(`\n   ${'TOTAL'.padEnd(22)} → ${products.length} products`);

  } catch (err) {
    console.error('❌ Seed error:', err);
  } finally {
    mongoose.disconnect();
    console.log('\n🔌 MongoDB connection closed');
  }
}